[package]
name = "multi-key-dep"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.14"

[target.'cfg(unix)'.dependencies]
cc = "1.0.3"
log-once = "0.3.1"

[dev-dependencies]
log-once = "0.3.1"

[build-dependencies]
rand = "0.8.5"
