name: 'cargo-machete'

description: 'A github action for cargo machete'

author: 'Cargo machete community'

branding:
  color: "black"
  icon: "code"

inputs:
  args:
    description: 'Extra arguments to pass to the `cargo-machete` invoke'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Install precompiled or compile `cargo-machete`
      id: download
      shell: bash
      run: $GITHUB_ACTION_PATH/action/entrypoint.sh

    - name: Run `cargo-machete`
      shell: bash
      run: |
        cargo-machete ${{ inputs.args }}
