name: 'cargo-machete'
description: 'A github action for cargo machete'
author: 'Cargo machete community'
branding:
  color: "black"
  icon: "code"
runs:
  using: composite
  steps:
    - name: Install cargo-machete
      uses: clechasseur/rs-cargo@v4
      with:
        command: install
        args: cargo-machete@0.9.1
        toolchain: stable
    - name: Machete
      uses: clechasseur/rs-cargo@v4
      with:
        command: machete
