[package]
name = "renamed-dep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustls-webpki.workspace = true
bytes.workspace = true
flagset.workspace = true
