[workspace]
members = ["./inner"]

[workspace.dependencies]
log = "0.4.14"
serde = "1"

[workspace.metadata.cargo-machete]
ignored = [
    "lazy_static",
    "serde",
    "futures", # actually used but in workspace ignored, should NOT cause a warning
]